### ISSUE TITLE
Antrag_stellen Prüfung auf Start & Enddatum sendet immer Hinweis, nicht nur wenn auftritt

### ISSUE THREAD

**Issue by maxseidlitz** [maxseidlitz/Urlaubsantragsverwaltung#10]
Bekomme beim "Antrag stellen" immer eine Meldung, dass Startdatum vor Enddatum liegen muss - obwohl es das tut.
<img width="1575" alt="Bildschirmfoto 2023-11-21 um 16 49 12" src="https://github.com/maxseidlitz/Urlaubsantragsverwaltung/assets/61022094/f6a64d44-0fd1-4a36-9b5a-7048f85e8442">

Bin gerade auf dem aktuellen branch mit einem neuen User.

**Comment by Raspi-it** [comment]
kann den Fehler nicht reproduzieren. Allerdings müsste die Fehlermeldung kommen (da du dass ja anscheinend gestern erstellt hast), dass das Startdatum mindestens morgen beginnen muss. Und lokale habe ich noch den Fehler festgestellt, dass trotz einer validen Fehlermeldung der Antrag abgespeichert wird.

**Comment by maxseidlitz** [comment]
@Raspi-it war zu voreilig. DU hast vollkommen Recht: Die fehlermeldung muss kommen. Streiche die Issue also.
