### ISSUE TITLE
Benutzeranmeldung programmieren

### ISSUE THREAD

**Issue by maxseidlitz** [maxseidlitz/Urlaubsantragsverwaltung#3]

**Comment by Raspi-it** [comment]
Problem with foreign key
![grafik](https://github.com/maxseidlitz/Urlaubsantragsverwaltung/assets/59459856/573f8ecc-2f7b-4702-92a6-64c183e90d5e)

**Comment by Raspi-it** [comment]
Solved via JWT tokens. Users can now authenticate against the server. Authorization is next topic
